
name: Get ENS



on: 
  push:
    branches:
      - main
  schedule:
    - cron:  '0 3 * * 1'

jobs:
  get_ens_to_sqlite:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Set up Python 3.7
        uses: actions/setup-python@main
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pytz
          pip install --upgrade google-cloud-bigquery
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GETENSKEY }}
          export_default_credentials: true
      - name: Get ENS
        run: |
          python ./get_ENS.py
      - name: upload ens.zip
        uses: actions/upload-artifact@main
        with:
          name: ENS
          path: outputs/
      - name: zip ENS file
        run: |
          cd outputs
          zip -r ENS.zip ENS
#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           allowUpdates: true
#           tag_name: ENS_Release_Test
#           release_name: ENS Release_Test
#           draft: false
#           prerelease: false
      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          tag: ENS_Release 
          assets: ENS.zip
      
      - name: Upload new Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/KeystoneHQ/ENS-meta-repo/releases/48169222/assets{?name,label}
          asset_path: ./outputs/ENS.zip
          asset_name: ENS.zip
          asset_content_type: application/zip
          
